[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd agent && npm ci && npx playwright install --with-deps chromium"]

[phases.build]

[start]
cmd = "cd agent && node one-off-create-safe-proof.mjs && node index.js"
