// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9AqyTWvKXUWWO7yvRx04ocIxwes4A9lM',
    appId: '1:104806196241:web:e2e3487afdbe5dcc8cbdb0',
    messagingSenderId: '104806196241',
    projectId: 'na4qizroum13ep8ua6w67dmwt5cl8a',
    authDomain: 'na4qizroum13ep8ua6w67dmwt5cl8a.firebaseapp.com',
    storageBucket: 'na4qizroum13ep8ua6w67dmwt5cl8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvVyC65dNlTa-a1hMs0TxvxGm8oxaKJQw',
    appId: '1:104806196241:android:a1c8ec49f62dbcfe8cbdb0',
    messagingSenderId: '104806196241',
    projectId: 'na4qizroum13ep8ua6w67dmwt5cl8a',
    storageBucket: 'na4qizroum13ep8ua6w67dmwt5cl8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIgQOGX36n7OVR2D2NCWF62yIyXrTIDYc',
    appId: '1:104806196241:ios:4e6e0c95cd4d2a728cbdb0',
    messagingSenderId: '104806196241',
    projectId: 'na4qizroum13ep8ua6w67dmwt5cl8a',
    storageBucket: 'na4qizroum13ep8ua6w67dmwt5cl8a.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
